artifact_location: /Users/davinci/Desktop/tickets_clasificator/mlflow_tracking_data/218802408105393737
creation_time: 1747775480701
experiment_id: '218802408105393737'
last_update_time: 1747775480701
lifecycle_stage: active
name: Baseline_Clasificacion_tickets_ada
