artifact_uri: /Users/davinci/Desktop/tickets_clasificator/mlflow_tracking_data/218802408105393737/b26e1e8e0f1c453b98c8ec4c9c917b1a/artifacts
end_time: 1747776407686
entry_point_name: ''
experiment_id: '218802408105393737'
lifecycle_stage: active
run_id: b26e1e8e0f1c453b98c8ec4c9c917b1a
run_name: Naive Bayes Multinomial
run_uuid: b26e1e8e0f1c453b98c8ec4c9c917b1a
source_name: ''
source_type: 4
source_version: ''
start_time: 1747776405437
status: 3
tags: []
user_id: davinci
