artifact_location: /Users/davinci/Desktop/tickets_clasificator/mlflow_tracking_data/0
creation_time: 1747775480695
experiment_id: '0'
last_update_time: 1747775480695
lifecycle_stage: active
name: Default
