artifact_uri: /Users/davinci/Desktop/tickets_clasificator/mlflow_tracking_data/218802408105393737/cdf5d9d8d5ae4e62b55136eaa3673d01/artifacts
end_time: 1747775492430
entry_point_name: ''
experiment_id: '218802408105393737'
lifecycle_stage: active
run_id: cdf5d9d8d5ae4e62b55136eaa3673d01
run_name: KNN (K-Nearest Neighbors)
run_uuid: cdf5d9d8d5ae4e62b55136eaa3673d01
source_name: ''
source_type: 4
source_version: ''
start_time: 1747775489736
status: 3
tags: []
user_id: davinci
